
spring:
  application:
    name: find-users-service

server:
  servlet:
    context-path: /find-users

application:
  base-backend-url: https://bpdts-test-app.herokuapp.com
  city-endpoint: /city/London/users
  users-endpoint: /users
